### ISSUE TITLE
Feedback homework 2

### ISSUE THREAD

**Issue by Toinne** [NelsonNaja/html-css#4]
Good Job !

Cool that you did the floats exercise also even though it was not required.
You even found a way around the collapse problem 👏.
Good work on the effects !

Some remarks:

```
#grid-floats .grid-item {
    position: relative;
    ...
}
```
This does not have an effect. This is only useful if you want to position a child element in the grid-item absolute. 

```
#grid-flex .grid-item {
    align-content: flex-start;
    flex-wrap: nowrap;
}
```
These properties have no effect on the child items.

```
@media only screen
  and (min-device-width: 768px)
  and (max-device-width: 1024px)
  and (-webkit-min-device-pixel-ratio: 1) {


    #grid-flex {
        display: flex;
```
No need to repeat this in your media query all rules outside of a media query will still be applied.

```
#grid-flex .grid-item {
    width: 300px;
```
Instead of setting a fixed width on the element try using the flex property.
Remove the `width` and check what this does `flex: 1 1 300px;`.
You should get this way nicer effect.
<img width="1393" alt="Screen Shot 2019-06-08 at 11 29 53" src="https://user-images.githubusercontent.com/2686028/59145195-cd351b00-89e0-11e9-815f-b1089db96025.png">

**Comment by NelsonNaja** [comment]
Thanks Antoni... but maybe there is a confuse.
```
 **This is not my code**:  #grid-floats .grid-item {    position: relative;
 **My code is**: .grid-item {  float: left;} 
```
```
 **This is not my code**:
#grid-flex .grid-item {
    align-content: flex-start;
    flex-wrap: nowrap;
}
 **My code is**: 
#grid-flex{
   display:flex;
   flex-flow: wrap;
   }
```
```
 **This is not my*:
(-webkit-min-device-pixel-ratio: 1) 
```
```
**This is not my*: #grid-flex .grid-item {   width: 300px;
In this part I used porcentages  .grid-item { width:22%;} 
```
But  I going to read about  flex property  that you recomended me.

And finally my homework  look a littler different :-) 

![emage](https://user-images.githubusercontent.com/50958575/59193055-be876900-8b84-11e9-886c-3caa90828b53.png)

Thank You Antoni.
